Hbase Batch Get Support
oceanbase/obkv-table-client-java pull request #269
Opened 2024-12-24 03:08 UTC by JackShi148

## Summary

This client has supported OBKV HBase Get feature in LSOp.

## Solution Description

Adjust ObTableSingelOp, ObTableSingelOpQuery and ObTableClientLSBatchOpsImpl to OBKV HBase Get. ObTableSingelOpQuery will carry elements required by OBKV HBase Get and ObTableClientLSBatchOpsImpl will send them to server.

2024-12-24 03:25 UTC, shenyunlong requested changes

2024-12-24 03:25 UTC, shenyunlong commented on src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
> +               || OB_VERSION >= OB_VERSION_4_3_5_0;
batch GET 在 4.3.5 已经支持了吗？不是还没有 patch 过去

2024-12-24 03:25 UTC, shenyunlong commented on src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
> +                isHBaseQuery = true;
这里的逻辑看上去是，只要第一个 query 是 Hbase query，那么这个 queries 就都是 hbase query，这个是否符合预期，另外如果只判断第一个没有必要 for 循环

2024-12-24 03:25 UTC, shenyunlong commented on src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
> +        if (isHbaseQuery && ObGlobal.isHBaseBatchGetSupport()) {
如果 hbase query，但是服务端不支持，这里看上去只是不序列化这部分成员，但是不报错，这个是否符合预期？

2024-12-24 03:35 UTC, JackShi148 commented on src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
> +        if (isHbaseQuery && ObGlobal.isHBaseBatchGetSupport()) {
如果 hbase query，但是服务端不支持的话，会在OBKV HBase 侧报错。因为之前LS Batch 不会处理 hbase query，所以走到这里的 hbase query 都是服务端版本支持的。这里做的版本兼容主要是为了防止 table 的query 会序列化 hbase query 的成员。

2024-12-24 03:42 UTC, JackShi148 commented on src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
> +                isHBaseQuery = true;
已经修改成判非空且长度大于0，获取第一个

2024-12-24 03:49 UTC, WeiXinChan approved these changes

2024-12-24 06:05 UTC, JackShi148 commented on src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
> +               || OB_VERSION >= OB_VERSION_4_3_5_0;
已修改

2025-01-02 12:19 UTC, shenyunlong commented
LGTM

2025-01-02 12:19 UTC, merged